#!/usr/bin/env bash

set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
build_dir="$root/build"
obj_dir="$build_dir/obj"
generated_dir="$build_dir/generated"
kernel_include_dir="$root/kernel/include"

llvm_bin="${LIQUIDOS_LLVM_BIN:-$(brew --prefix llvm 2>/dev/null)/bin}"
clang="${LIQUIDOS_CLANG:-$llvm_bin/clang}"
lld="${LIQUIDOS_LLD:-$(brew --prefix lld 2>/dev/null)/bin/ld.lld}"
objcopy="${LIQUIDOS_OBJCOPY:-$llvm_bin/llvm-objcopy}"
nasm="${LIQUIDOS_NASM:-$(command -v nasm || true)}"

for tool in "$clang" "$lld" "$objcopy" "$nasm"; do
    if [[ -z "$tool" || ! -x "$tool" ]]; then
        echo "Missing build tool: ${tool:-nasm}" >&2
        echo "Install the dependencies with: brew install llvm lld nasm" >&2
        exit 1
    fi
done

rm -rf "$obj_dir" "$generated_dir"
mkdir -p "$obj_dir" "$generated_dir"

echo "[LiquidOS] Compiling x86_64 kernel"

objects=()
entry_src="$root/kernel/arch/x86_64/entry.asm"
entry_obj="$obj_dir/entry.o"
"$nasm" -f elf64 -o "$entry_obj" "$entry_src"
objects+=("$entry_obj")

while IFS= read -r file; do
    [[ "$file" == "$entry_src" ]] && continue
    relative="${file#"$root/kernel/"}"
    object_name="${relative//\//_}"
    object_path="$obj_dir/${object_name%.asm}.o"
    "$nasm" -f elf64 -o "$object_path" "$file"
    objects+=("$object_path")
done < <(find "$root/kernel/arch/x86_64" -type f -name '*.asm' | sort)

while IFS= read -r file; do
    relative="${file#"$root/kernel/"}"
    object_name="${relative//\//_}"
    object_path="$obj_dir/${object_name%.c}.o"
    "$clang" \
        -target x86_64-unknown-none-elf \
        -std=c11 \
        -O2 \
        -ffreestanding \
        -fno-builtin \
        -fno-stack-protector \
        -fno-pic \
        -fno-asynchronous-unwind-tables \
        -mno-red-zone \
        -mno-sse \
        -mno-sse2 \
        -Wall \
        -Wextra \
        -I "$kernel_include_dir" \
        -c "$file" \
        -o "$object_path"
    objects+=("$object_path")
done < <(find "$root/kernel" -type f -name '*.c' | sort)

kernel_elf="$build_dir/kernel.elf"
kernel_bin="$build_dir/kernel.bin"
kernel_padded="$build_dir/kernel.pad.bin"

"$lld" -flavor gnu \
    -T "$root/kernel/linker.ld" \
    -nostdlib \
    -z max-page-size=0x1000 \
    -o "$kernel_elf" \
    "${objects[@]}"
"$objcopy" -O binary "$kernel_elf" "$kernel_bin"

kernel_bytes="$(wc -c < "$kernel_bin" | tr -d ' ')"
kernel_sectors="$(( (kernel_bytes + 511) / 512 ))"
if (( kernel_sectors < 1 || kernel_sectors > 1024 )); then
    echo "Kernel uses $kernel_sectors sectors; expected between 1 and 1024." >&2
    exit 1
fi

cp "$kernel_bin" "$kernel_padded"
truncate -s "$((kernel_sectors * 512))" "$kernel_padded"

cat > "$generated_dir/kernel_layout.inc" <<EOF
; Generated by scripts/build-macos.sh. Do not edit by hand.
%define KERNEL_SECTOR_COUNT $kernel_sectors
%define KERNEL_SIZE_BYTES $kernel_bytes
EOF

echo "[LiquidOS] Assembling bootloader"

stage1_bin="$build_dir/stage1.bin"
stage2_bin="$build_dir/stage2.bin"
stage2_padded="$build_dir/stage2.pad.bin"

"$nasm" -f bin -I "$root/boot/include/" -o "$stage1_bin" "$root/boot/stage1/stage1.asm"
stage1_bytes="$(wc -c < "$stage1_bin" | tr -d ' ')"
if [[ "$stage1_bytes" != "512" ]]; then
    echo "Stage 1 must be exactly 512 bytes; got $stage1_bytes." >&2
    exit 1
fi

signature="$(tail -c 2 "$stage1_bin" | od -An -tx1 | tr -d ' \n')"
if [[ "$signature" != "55aa" ]]; then
    echo "Stage 1 is missing the BIOS boot signature 55 AA." >&2
    exit 1
fi

"$nasm" -f bin \
    -I "$generated_dir/" \
    -I "$root/boot/include/" \
    -o "$stage2_bin" \
    "$root/boot/stage2/stage2.asm"

stage2_bytes="$(wc -c < "$stage2_bin" | tr -d ' ')"
stage2_max_bytes="$((16 * 512))"
if (( stage2_bytes > stage2_max_bytes )); then
    echo "Stage 2 is $stage2_bytes bytes; maximum is $stage2_max_bytes." >&2
    exit 1
fi

cp "$stage2_bin" "$stage2_padded"
truncate -s "$stage2_max_bytes" "$stage2_padded"

image="$build_dir/liquidos.img"
truncate -s "$((1440 * 1024))" "$image"
dd if="$stage1_bin" of="$image" conv=notrunc status=none
dd if="$stage2_padded" of="$image" bs=512 seek=1 conv=notrunc status=none
dd if="$kernel_padded" of="$image" bs=512 seek=17 conv=notrunc status=none

echo
echo "Build complete."
echo "Stage 1: $stage1_bin (512 bytes)"
echo "Stage 2: $stage2_bin ($stage2_bytes bytes, padded to $stage2_max_bytes bytes)"
echo "Kernel:  $kernel_bin ($kernel_bytes bytes, $kernel_sectors sectors)"
echo "Image:   $image"
