$ErrorActionPreference = "Stop"
. "$PSScriptRoot\common.ps1"

$root = Get-ProjectRoot
$buildDir = Get-BuildDir
$objDir = Join-Path $buildDir "obj"
$generatedDir = Join-Path $buildDir "generated"
New-Item -ItemType Directory -Force -Path $objDir, $generatedDir | Out-Null

$nasm = Find-Nasm
$clang = Find-Clang
$lld = Find-Lld
$objcopy = Find-Objcopy

$includeDir = (Join-Path $root "boot\include") + [System.IO.Path]::DirectorySeparatorChar
$generatedIncludeDir = $generatedDir + [System.IO.Path]::DirectorySeparatorChar
$kernelIncludeDir = Join-Path $root "kernel\include"

$kernelElf = Join-Path $buildDir "kernel.elf"
$kernelBin = Join-Path $buildDir "kernel.bin"
$kernelPadded = Join-Path $buildDir "kernel.pad.bin"
$kernelLayout = Join-Path $generatedDir "kernel_layout.inc"

& "$PSScriptRoot\generate-ui-font.ps1" -Quiet
& "$PSScriptRoot\generate-system-icons.ps1" | Out-Null

Write-Step "Compiling x86_64 kernel"

$objects = New-Object System.Collections.Generic.List[string]

$entryAsm = Join-Path $root "kernel\arch\x86_64\entry.asm"
$entryObj = Join-Path $objDir "entry.o"
Invoke-CheckedCommand $nasm @("-f", "elf64", "-o", $entryObj, $entryAsm)
$objects.Add($entryObj)

$asmFiles = Get-ChildItem -Path (Join-Path $root "kernel\arch\x86_64") -Recurse -Filter *.asm | Where-Object { $_.FullName -ne $entryAsm } | Sort-Object FullName
foreach ($file in $asmFiles) {
    $relative = $file.FullName.Substring((Join-Path $root "kernel").Length + 1)
    $objectName = ($relative -replace '[\\/]', '_') -replace '\.asm$', '.o'
    $objectPath = Join-Path $objDir $objectName
    Invoke-CheckedCommand $nasm @("-f", "elf64", "-o", $objectPath, $file.FullName)
    $objects.Add($objectPath)
}

$cFiles = Get-ChildItem -Path (Join-Path $root "kernel") -Recurse -Filter *.c | Sort-Object FullName
foreach ($file in $cFiles) {
    $relative = $file.FullName.Substring((Join-Path $root "kernel").Length + 1)
    $objectName = ($relative -replace '[\\/]', '_') -replace '\.c$', '.o'
    $objectPath = Join-Path $objDir $objectName

    Invoke-CheckedCommand $clang @(
        "-target", "x86_64-unknown-none-elf",
        "-std=c11",
        "-O2",
        "-ffreestanding",
        "-fno-builtin",
        "-fno-stack-protector",
        "-fno-pic",
        "-fno-asynchronous-unwind-tables",
        "-mno-red-zone",
        "-mno-sse",
        "-mno-sse2",
        "-Wall",
        "-Wextra",
        "-I", $kernelIncludeDir,
        "-c", $file.FullName,
        "-o", $objectPath
    )
    $objects.Add($objectPath)
}

$linkerScript = Join-Path $root "kernel\linker.ld"
$linkArgs = @("-flavor", "gnu", "-T", $linkerScript, "-nostdlib", "-z", "max-page-size=0x1000", "-o", $kernelElf) + $objects.ToArray()
Invoke-CheckedCommand $lld $linkArgs
Invoke-CheckedCommand $objcopy @("-O", "binary", $kernelElf, $kernelBin)

$kernelBytes = [System.IO.File]::ReadAllBytes($kernelBin)
$kernelSectorCount = [int][Math]::Ceiling($kernelBytes.Length / 512.0)
$kernelMaxSectors = 1240
if ($kernelSectorCount -lt 1) {
    throw "Kernel binary is empty."
}
if ($kernelSectorCount -gt $kernelMaxSectors) {
    throw "Kernel uses $kernelSectorCount sectors, but the boot image reserves at most $kernelMaxSectors sectors."
}

$paddedKernel = New-Object byte[] ($kernelSectorCount * 512)
[System.Array]::Copy($kernelBytes, 0, $paddedKernel, 0, $kernelBytes.Length)
[System.IO.File]::WriteAllBytes($kernelPadded, $paddedKernel)

@"
; Generated by scripts\build.ps1. Do not edit by hand.
%define KERNEL_SECTOR_COUNT $kernelSectorCount
%define KERNEL_SIZE_BYTES $($kernelBytes.Length)
"@ | Set-Content -NoNewline -Encoding ASCII $kernelLayout

Write-Step "Assembling bootloader"

$stage1Src = Join-Path $root "boot\stage1\stage1.asm"
$stage2Src = Join-Path $root "boot\stage2\stage2.asm"
$stage1Bin = Join-Path $buildDir "stage1.bin"
$stage2Bin = Join-Path $buildDir "stage2.bin"
$stage2Padded = Join-Path $buildDir "stage2.pad.bin"

Invoke-CheckedCommand $nasm @("-f", "bin", "-I$includeDir", "-o", $stage1Bin, $stage1Src)

$stage1Bytes = [System.IO.File]::ReadAllBytes($stage1Bin)
if ($stage1Bytes.Length -ne 512) {
    throw "Stage 1 must be exactly 512 bytes, but it is $($stage1Bytes.Length) bytes."
}

if (($stage1Bytes[510] -ne 0x55) -or ($stage1Bytes[511] -ne 0xAA)) {
    throw "Stage 1 does not end with the BIOS boot signature 55 AA."
}

Invoke-CheckedCommand $nasm @("-f", "bin", "-I$generatedIncludeDir", "-I$includeDir", "-o", $stage2Bin, $stage2Src)

$stage2Bytes = [System.IO.File]::ReadAllBytes($stage2Bin)
$stage2MaxBytes = 16 * 512

if ($stage2Bytes.Length -gt $stage2MaxBytes) {
    throw "Stage 2 is $($stage2Bytes.Length) bytes, but the boot image reserves only $stage2MaxBytes bytes."
}

$paddedStage2 = New-Object byte[] $stage2MaxBytes
[System.Array]::Copy($stage2Bytes, 0, $paddedStage2, 0, $stage2Bytes.Length)
[System.IO.File]::WriteAllBytes($stage2Padded, $paddedStage2)

Write-Host ""
Write-Host "Build complete." -ForegroundColor Green
Write-Host "Stage 1: $stage1Bin (512 bytes)"
Write-Host "Stage 2: $stage2Bin ($($stage2Bytes.Length) bytes, padded to $stage2MaxBytes bytes)"
Write-Host "Kernel:  $kernelBin ($($kernelBytes.Length) bytes, $kernelSectorCount sectors)"
Write-Host "Reserve: $kernelMaxSectors sectors"
